### ISSUE TITLE
pre-process synchronized audio-video streams

### ISSUE THREAD

**Issue by LindgeW** [YUCHEN005/GILA#1]
Hi, 

Could you give more details about how to pre-process the synchronized audio-video input streams (mentioned in Sec 3.1) ?  whether including the temporal alignment?

Thanks!

**Comment by YUCHEN005** [comment]
Hi, we just follow the preprocessing steps of AV-Hubert in https://github.com/facebookresearch/av_hubert/tree/main/avhubert/preparation
